---

## FIXME! or ssl ?
- name: Configure apache
  template:
    src: apache2-misp.conf.j2
    dest: "{{ apache_sitedir }}/misp.conf"
    mode: '0644'
    backup: yes
  notify:
    - restart webserver
    - restart webserver - docker,debian
    - restart webserver - docker,redhat

- name: Debian | Disable default apache config
  file: dest=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - restart webserver
    - restart webserver - docker,debian
    - restart webserver - docker,redhat
  when: ansible_os_family == 'Debian'

- name: debian | ensure required modules are present
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - headers
    - rewrite
  notify:
    - restart webserver
    - restart webserver - docker,debian
    - restart webserver - docker,redhat
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Debian | Enable misp apache config
  file:
    src: "{{ apache_sitedir }}/misp.conf"
    dest: /etc/apache2/sites-enabled/misp.conf
    state: link
  notify:
    - restart webserver
    - restart webserver - docker,debian
    - restart webserver - docker,redhat
  when: ansible_os_family == 'Debian'
